package com.cmp.community.healers.softskilltraining.data.remote.api

import com.cmp.community.healers.softskilltraining.core.network.ApiConstants
import com.cmp.community.healers.softskilltraining.core.network.NetworkResult
import com.cmp.community.healers.softskilltraining.core.network.httpClient
import com.cmp.community.healers.softskilltraining.data.remote.dto.request.InitiatePaymentRequest
import com.cmp.community.healers.softskilltraining.data.remote.dto.request.ScheduleExamRequest
import com.cmp.community.healers.softskilltraining.data.remote.dto.request.UpdateProfileRequest
import com.cmp.community.healers.softskilltraining.data.remote.dto.response.CandidateProfileApiResponse
import com.cmp.community.healers.softskilltraining.data.remote.dto.response.CandidateProfileData
import com.cmp.community.healers.softskilltraining.data.remote.dto.response.CitiesApiResponse
import com.cmp.community.healers.softskilltraining.data.remote.dto.response.CityData
import com.cmp.community.healers.softskilltraining.data.remote.dto.response.PaymentInitiateApiResponse
import com.cmp.community.healers.softskilltraining.data.remote.dto.response.PaymentInitiateData
import io.ktor.client.*
import io.ktor.client.call.*
import io.ktor.client.plugins.*
import io.ktor.client.request.*
import io.ktor.client.request.forms.*
import io.ktor.client.statement.*
import io.ktor.http.*
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

class CandidateApi(private val client: HttpClient = httpClient) {

    // ── Get profile ──────────────────────────────────────────────────────────
    suspend fun getProfile(accessToken: String): NetworkResult<CandidateProfileData> = safeCall {
        val response = client.get(url(ApiConstants.Endpoints.CANDIDATE_ME)) {
            header(HttpHeaders.Authorization, "Bearer $accessToken")
        }
        if (response.status.isSuccess()) {
            NetworkResult.Success(response.body<CandidateProfileApiResponse>().data)
        } else {
            NetworkResult.Error(parseError(response.bodyAsText()), response.status.value)
        }
    }

    // ── Update profile ───────────────────────────────────────────────────────
    suspend fun updateProfile(
        accessToken: String,
        request: UpdateProfileRequest   // city in request is String? — omitted when null
    ): NetworkResult<Unit> = safeCall {
        val response = client.put(url(ApiConstants.Endpoints.CANDIDATE_ME)) {
            header(HttpHeaders.Authorization, "Bearer $accessToken")
            contentType(ContentType.Application.Json)
            setBody(request)
        }
        if (response.status.isSuccess()) NetworkResult.Success(Unit)
        else NetworkResult.Error(parseError(response.bodyAsText()), response.status.value)
    }

    // ── Upload document ──────────────────────────────────────────────────────
    // Content-Disposition in extra headers must only contain filename=...
    // The name="file" part is auto-generated by Ktor from the key parameter.
    suspend fun uploadDocument(
        accessToken: String,
        type: String,
        fileBytes: ByteArray,
        fileName: String
    ): NetworkResult<Unit> = safeCall {
        val mimeType = resolveMimeType(fileName)
        val response = client.post(url(ApiConstants.Endpoints.CANDIDATE_DOCUMENTS)) {
            header(HttpHeaders.Authorization, "Bearer $accessToken")
            setBody(MultiPartFormDataContent(
                formData {
                    append("type", type)
                    append("file", fileBytes, Headers.build {
                        append(HttpHeaders.ContentType, mimeType)
                        append(HttpHeaders.ContentDisposition, "filename=\"$fileName\"")
                    })
                }
            ))
        }
        if (response.status.isSuccess()) NetworkResult.Success(Unit)
        else NetworkResult.Error(parseError(response.bodyAsText()), response.status.value)
    }

    // ── Get cities ───────────────────────────────────────────────────────────
    suspend fun getCities(accessToken: String): NetworkResult<List<CityData>> = safeCall {
        val response = client.get(url(ApiConstants.Endpoints.CITIES)) {
            header(HttpHeaders.Authorization, "Bearer $accessToken")
        }
        if (response.status.isSuccess()) {
            // Response is double-nested: outer.data.data contains the actual list
            NetworkResult.Success(response.body<CitiesApiResponse>().data.data)
        } else {
            NetworkResult.Error(parseError(response.bodyAsText()), response.status.value)
        }
    }

    // ── Initiate payment ─────────────────────────────────────────────────────
    suspend fun initiatePayment(accessToken: String): NetworkResult<PaymentInitiateData> = safeCall {
        val response = client.post(url(ApiConstants.Endpoints.INITIATE_PAYMENT)) {
            header(HttpHeaders.Authorization, "Bearer $accessToken")
            contentType(ContentType.Application.Json)
            setBody(InitiatePaymentRequest())
        }
        val body = response.bodyAsText()
        if (response.status.isSuccess()) {
            NetworkResult.Success(response.body<PaymentInitiateApiResponse>().data)
        } else {
            NetworkResult.Error(parseError(body), response.status.value)
        }
    }

    // ── Schedule exam ────────────────────────────────────────────────────────
    suspend fun scheduleExam(
        accessToken: String,
        examDate: String           // "YYYY-MM-DD"
    ): NetworkResult<Unit> = safeCall {
        val response = client.post(url(ApiConstants.Endpoints.CANDIDATE_SCHEDULE)) {
            header(HttpHeaders.Authorization, "Bearer $accessToken")
            contentType(ContentType.Application.Json)
            setBody(ScheduleExamRequest(examDate))
        }
        if (response.status.isSuccess()) NetworkResult.Success(Unit)
        else NetworkResult.Error(parseError(response.bodyAsText()), response.status.value)
    }

    private fun resolveMimeType(fileName: String): String = when {
        fileName.endsWith(".pdf",  ignoreCase = true) -> "application/pdf"
        fileName.endsWith(".png",  ignoreCase = true) -> "image/png"
        fileName.endsWith(".jpg",  ignoreCase = true) -> "image/jpeg"
        fileName.endsWith(".jpeg", ignoreCase = true) -> "image/jpeg"
        else                                          -> "application/octet-stream"
    }

    // ── Helpers ──────────────────────────────────────────────────────────────
    private fun url(endpoint: String) = ApiConstants.BASE_URL + endpoint

    private fun parseError(body: String): String = try {
        val json = Json.parseToJsonElement(body).jsonObject
        json["message"]?.jsonPrimitive?.content
            ?: json["error"]?.jsonPrimitive?.content
            ?: body.take(200).ifBlank { "Something went wrong." }
    } catch (e: Exception) {
        body.take(200).ifBlank { "Something went wrong." }
    }

    private suspend fun <T> safeCall(block: suspend () -> NetworkResult<T>): NetworkResult<T> =
        try { block() }
        catch (e: HttpRequestTimeoutException) {
            NetworkResult.Error("Request timed out. Please try again.")
        }
        catch (e: Exception) {
            NetworkResult.Error(e.message ?: "Network error. Please check your connection.")
        }
}