package com.cmp.community.healers.softskilltraining.theme

import com.cmp.community.healers.softskilltraining.utils.constants.document.DocumentType

data class AppStrings(
    // ── Auth - SignIn ──────────────────────────────────────────────────────────
    val welcomeBack: String,
    val welcomeBackSub: String,
    val phoneNumber: String,
    val phoneHint: String,
    val password: String,
    val passwordHint: String,
    val signIn: String,
    val noAccount: String,
    val signUp: String,

    // ── Auth - SignUp ──────────────────────────────────────────────────────────
    val createAccount: String,
    val createAccountSub: String,
    val firstName: String,
    val firstNameHint: String,
    val lastName: String,
    val lastNameHint: String,
    val emailAddress: String,
    val emailHint: String,
    val passwordCreateHint: String,
    val confirmPassword: String,
    val confirmPasswordHint: String,
    val alreadyAccount: String,

    // ── Auth - OTP ────────────────────────────────────────────────────────────
    val verificationCode: String,
    val otpSentTo: String,
    val verifyCode: String,
    val resendOtp: String,
    val didntReceive: String,
    val resend: String,
    val resendCodeIn: String,
    val otpExpired: String,

    // ── TopBar ────────────────────────────────────────────────────────────────
    val appTitle: String,
    val appSubtitle: String,
    val logout: String,
    val tabProfile: String,
    val tabApplication: String,

    // ── Registration ──────────────────────────────────────────────────────────
    val completeRegistration: String,
    val completeRegistrationSub: String,
    val personalInfo: String,
    val personalInfoSub: String,
    val fatherName: String,
    val fatherNameHint: String,
    val cnicNumber: String,
    val cnicHint: String,
    val dateOfBirth: String,
    val dobHint: String,
    val contactNumber: String,
    val cityArea: String,
    val cityHint: String,
    val address: String,
    val addressHint: String,
    val ok: String,
    val cancel: String,
    val docUpload: String,
    val docUploadSub: String,
    val docWarning: String,
    val educationDeclaration: String,
    val educationSub: String,
    val sixteenYears: String,
    val sixteenYearsSub: String,
    val uploadDegree: String,
    val uploadDegreeHint: String,
    val changeFile: String,
    val upload: String,
    val step1Label: String,
    val continueToPayment: String,

    // ── Application Progress ──────────────────────────────────────────────────
    val stepRegistration: String,
    val stepPayment: String,
    val stepTraining: String,
    val completeProfile: String,
    val pickDate: String,
    val appProgress: String,
    val appProgressSub: String,
    val currentStepLabel: String,

    // ── Profile ───────────────────────────────────────────────────────────────
    val email: String,
    val phone: String,
    val location: String,
    val appStatus: String,
    val registrationLabel: String,
    val completed: String,
    val trainingStatus: String,
    val notScheduled: String,
    val certificate: String,
    val pendingTraining: String,
    val pending: String,
    val fatherNameLabel: String,
    val cnicLabel: String,
    val dobLabel: String,
    val cityLabel: String,
    val addressLabel: String,
    val regDateLabel: String,
    val feePayment: String,
    val uploadedDocs: String,
    val view: String,
    val uploaded: String,
    val noDocs: String,
    val completeRegForDocs: String,
    val trainingDate: String,
    val trainingTime: String,
    val trainingCenter: String,
    val trainingAddress: String,
    val trainingCity: String,
    val trainingArrive: String,
    val noteLabel: String,

    // ── Scheduled Home ────────────────────────────────────────────────────────
    val trainingScheduled: String,
    val trainingScheduledSub: String,
    val goToProfile: String,

    // ── Payment ───────────────────────────────────────────────────────────────
    val paymentTitle: String,
    val paymentSub: String,
    val registrationFee: String,
    val paidBadge: String,
    val generateQr: String,
    val generating: String,
    val confirmPayment: String,
    val confirming: String,
    val transactionId: String,
    val paymentDate: String,
    val paymentSuccess: String,
    val downloadReceipt: String,
    val step2Label: String,
    val back: String,
    val continueToScheduling: String,
    val paymentProgressDone: String,
    val paymentProgressActive: String,
    val paymentProgressPending: String,
    val registrationFeeSub: String,
    val includedTaxes: String,
    val scanQrToPay: String,
    val verifying: String,
    val downloading: String,
    val statusLabel: String,
    val successLabel: String,
    val payFee: String,

    // ── Scheduling ────────────────────────────────────────────────────────────
    val scheduleTrainingTitle: String,
    val scheduleTrainingSub: String,
    val step3Label: String,
    val scheduling: String,
    val completeRegistrationBtn: String,

    // ── Congrats ──────────────────────────────────────────────────────────────
    val regComplete: String,
    val congratulations: String,
    val regCompletedSub: String,
    val trainingScheduleTitle: String,
    val trainingScheduleCardSub: String,
    val dateLabel: String,
    val timeLabel: String,
    val centerLabel: String,
    val whatsNext: String,
    val whatsNextItem1: String,
    val whatsNextItem2: String,
    val whatsNextItem3: String,
    val whatsNextItem4: String,
    val badgeRegistrationSub: String,
    val badgePaymentSub: String,
    val badgeTrainingSub: String,

    // ── Document / misc ───────────────────────────────────────────────────────
    val mandatory: String,
    val change: String,
    val paymentSuccessfulBanner: String,
    val proceedToSchedule: String,

    // ── Document types ────────────────────────────────────────────────────────
    val docCandidatePhoto: String,
    val docCnicFront: String,
    val docCnicBack: String,
    val docPassport: String,
    val docPoliceCert: String,
    val docMedicalCert: String,

    // ── Payment badge ─────────────────────────────────────────────────────────
    val paid: String,
    val unpaid: String,

    // ── Scheduling / Warning banners ──────────────────────────────────────────
    val paymentRequiredWarning: String,
    val selectDateWarning: String,
    val selectTrainingDateTitle: String,
    val chooseTrainingDate: String,
    val lastDaySchedule: String,
    val daysLeftSchedule: String,
    val daysRemainingSchedule: String,
    val selectWithinDays: String,
)

val englishStrings = AppStrings(
    welcomeBack           = "Welcome Back",
    welcomeBackSub        = "Sign in to access your candidate portal",
    phoneNumber           = "Phone Number",
    phoneHint             = "03001234567",
    password              = "Password",
    passwordHint          = "Enter your password",
    signIn                = "Sign In",
    noAccount             = "Don't have an account? ",
    signUp                = "Sign Up",

    createAccount         = "Create Account",
    createAccountSub      = "Sign up to get started with your candidate portal",
    firstName             = "First Name",
    firstNameHint         = "John",
    lastName              = "Last Name",
    lastNameHint          = "Doe",
    emailAddress          = "Email Address",
    emailHint             = "example@email.com",
    passwordCreateHint    = "Min. 8 characters",
    confirmPassword       = "Confirm Password",
    confirmPasswordHint   = "Re-enter your password",
    alreadyAccount        = "Already have an account? ",

    verificationCode      = "Verification Code",
    otpSentTo             = "We've sent a 6-digit code to ",
    verifyCode            = "Verify Code",
    resendOtp             = "Resend OTP",
    didntReceive          = "Didn't receive it? ",
    resend                = "Resend",
    resendCodeIn          = "Resend code in ",
    otpExpired            = "OTP expired. Tap Resend to get a new code.",

    appTitle              = "Soft Skill Training",
    appSubtitle           = "Candidate Portal",
    logout                = "Logout",
    tabProfile            = "Profile",
    tabApplication        = "Application",

    completeRegistration  = "Complete Your Registration",
    completeRegistrationSub = "Fill in your personal information, upload required documents, and declare your education",
    personalInfo          = "Personal Information",
    personalInfoSub       = "Enter your official details as per CNIC",
    fatherName            = "Father's Name",
    fatherNameHint        = "Aslam Khan",
    cnicNumber            = "CNIC Number",
    cnicHint              = "42201-XXXXXXX-X",
    dateOfBirth           = "Date of Birth",
    dobHint               = "DD/MM/YYYY",
    contactNumber         = "Contact Number",
    cityArea              = "City / Area",
    cityHint              = "Select your city",
    address               = "Address",
    addressHint           = "House #, Street #, Sector/Area",
    ok                    = "OK",
    cancel                = "Cancel",
    docUpload             = "Document Upload",
    docUploadSub          = "Upload high-quality scans of your original documents",
    docWarning            = "Please ensure all documents are clearly legible. Blurry or incorrect documents may lead to registration rejection. Max file size: 5MB.",
    educationDeclaration  = "Education Declaration",
    educationSub          = "Minimum education requirement is 10 years (Matric)",
    sixteenYears          = "16 Years of Education",
    sixteenYearsSub       = "Candidates with 16 years of education are eligible for advanced modules.",
    uploadDegree          = "Upload Degree Transcript / Certificate",
    uploadDegreeHint      = "Drag and drop your degree or tap to browse",
    changeFile            = "Change File",
    upload                = "Upload",
    step1Label            = "Step 1 of 3 • Registration",
    continueToPayment     = "Continue to Payment",

    stepRegistration      = "Registration",
    stepPayment           = "Payment",
    stepTraining          = "Training",
    completeProfile       = "Complete profile",
    pickDate              = "Pick training date",
    appProgress           = "Application Progress",
    appProgressSub        = "Complete all steps to receive your certification",
    currentStepLabel      = "Current Step",

    email                 = "Email",
    phone                 = "Phone",
    location              = "Location",
    appStatus             = "Application Status",
    registrationLabel     = "Registration",
    completed             = "Completed",
    trainingStatus        = "Training Status",
    notScheduled          = "Not Scheduled",
    certificate           = "Certificate",
    pendingTraining       = "Pending Training",
    pending               = "Pending",
    fatherNameLabel       = "Father's Name",
    cnicLabel             = "CNIC Number",
    dobLabel              = "Date of Birth",
    cityLabel             = "City",
    addressLabel          = "Address",
    regDateLabel          = "Registration Date",
    feePayment            = "Fee Payment",
    uploadedDocs          = "Uploaded Documents",
    view                  = "View",
    uploaded              = "Uploaded",
    noDocs                = "No documents uploaded yet",
    completeRegForDocs    = "Complete your registration to upload documents",
    trainingDate          = "Training Date",
    trainingTime          = "Training Time",
    trainingCenter        = "Training Center",
    trainingAddress       = "Address",
    trainingCity          = "City",
    trainingArrive        = "Please arrive 15 minutes early and bring a valid ID.",
    noteLabel             = "Note:",

    trainingScheduled     = "Training Already Scheduled",
    trainingScheduledSub  = "Your training session has been booked. Visit the Profile tab to view your schedule.",
    goToProfile           = "Go to Profile",

    paymentTitle          = "Registration Payment",
    paymentSub            = "Complete the payment to activate your candidate profile",
    registrationFee       = "Registration Fee",
    paidBadge             = "PAID",
    generateQr            = "Generate QR",
    generating            = "Generating...",
    confirmPayment        = "Confirm Payment",
    confirming            = "Confirming...",
    transactionId         = "Transaction ID",
    paymentDate           = "Payment Date",
    paymentSuccess        = "Payment Successful",
    downloadReceipt       = "Download Receipt",
    step2Label            = "Step 2 of 3 • Payment",
    back                  = "Back",
    continueToScheduling  = "Continue to Scheduling",
    paymentProgressDone   = "Registration",
    paymentProgressActive = "Payment",
    paymentProgressPending = "Schedule Training",
    registrationFeeSub    = "One-time registration fee to activate your candidate profile",
    includedTaxes         = "Included Taxes",
    scanQrToPay           = "Scan the QR code to pay PKR 5,000",
    verifying             = "Verifying...",
    downloading           = "Downloading...",
    statusLabel           = "Status",
    successLabel          = "Success",
    payFee                = "Pay PKR",

    scheduleTrainingTitle = "Schedule Your Training",
    scheduleTrainingSub   = "Select your preferred training date and complete the payment",
    step3Label            = "Step 3 of 3 • Scheduling",
    scheduling            = "Scheduling...",
    completeRegistrationBtn = "Complete Registration",

    regComplete           = "Registration Complete",
    congratulations       = "Congratulations! 🎉",
    regCompletedSub       = "Your registration has been completed and your training has been scheduled successfully",
    trainingScheduleTitle = "Training Schedule",
    trainingScheduleCardSub = "Your scheduled training details",
    dateLabel             = "Date",
    timeLabel             = "Time",
    centerLabel           = "Center",
    whatsNext             = "What's Next?",
    whatsNextItem1        = "Visit your assigned center on the scheduled date",
    whatsNextItem2        = "Bring your original CNIC for identity verification",
    whatsNextItem3        = "The center admin will initiate your training",
    whatsNextItem4        = "20 questions in 20 minutes - be prepared!",
    badgeRegistrationSub  = "Complete",
    badgePaymentSub       = "Received",
    badgeTrainingSub      = "Scheduled",

    mandatory             = "MANDATORY",
    change                = "Change",
    paymentSuccessfulBanner = "Payment Successful!",
    proceedToSchedule     = "You can now proceed to schedule your training",

    docCandidatePhoto     = "Candidate Photo",
    docCnicFront          = "CNIC Front",
    docCnicBack           = "CNIC Back",
    docPassport           = "Passport",
    docPoliceCert         = "Police Clearance Certificate",
    docMedicalCert        = "Medical Certificate",

    paid                  = "Paid",
    unpaid                = "Unpaid",

    paymentRequiredWarning = "Please complete the payment to proceed to training scheduling",
    selectDateWarning     = "Please select a training date to complete your scheduling",
    selectTrainingDateTitle = "Select Training Date",
    chooseTrainingDate    = "Choose your preferred training date",
    lastDaySchedule       = "Last day to schedule your exam!",
    daysLeftSchedule      = "left to schedule your exam",
    daysRemainingSchedule = "days remaining to schedule your exam",
    selectWithinDays      = "Select any date within the next 7 days",
)

val urduStrings = AppStrings(
    welcomeBack           = "خوش آمدید",
    welcomeBackSub        = "اپنے کینڈیڈیٹ پورٹل تک رسائی کے لیے سائن ان کریں",
    phoneNumber           = "فون نمبر",
    phoneHint             = "03001234567",
    password              = "پاس ورڈ",
    passwordHint          = "اپنا پاس ورڈ درج کریں",
    signIn                = "سائن ان",
    noAccount             = "اکاؤنٹ نہیں ہے؟ ",
    signUp                = "سائن اپ",

    createAccount         = "اکاؤنٹ بنائیں",
    createAccountSub      = "اپنے کینڈیڈیٹ پورٹل کے ساتھ شروع کریں",
    firstName             = "پہلا نام",
    firstNameHint         = "احمد",
    lastName              = "آخری نام",
    lastNameHint          = "علی",
    emailAddress          = "ای میل ایڈریس",
    emailHint             = "example@email.com",
    passwordCreateHint    = "کم از کم 8 حروف",
    confirmPassword       = "پاس ورڈ کی تصدیق",
    confirmPasswordHint   = "پاس ورڈ دوبارہ درج کریں",
    alreadyAccount        = "پہلے سے اکاؤنٹ ہے؟ ",

    verificationCode      = "تصدیقی کوڈ",
    otpSentTo             = "ہم نے 6 ہندسوں کا کوڈ بھیجا ہے ",
    verifyCode            = "کوڈ تصدیق کریں",
    resendOtp             = "OTP دوبارہ بھیجیں",
    didntReceive          = "کوڈ نہیں ملا؟ ",
    resend                = "دوبارہ بھیجیں",
    resendCodeIn          = "دوبارہ بھیجیں ",
    otpExpired            = "OTP میعاد ختم۔ نیا کوڈ حاصل کرنے کے لیے دوبارہ بھیجیں۔",

    appTitle              = "سافٹ اسکل ٹریننگ",
    appSubtitle           = "کینڈیڈیٹ پورٹل",
    logout                = "لاگ آؤٹ",
    tabProfile            = "پروفائل",
    tabApplication        = "درخواست",

    completeRegistration  = "رجسٹریشن مکمل کریں",
    completeRegistrationSub = "ذاتی معلومات بھریں، ضروری دستاویزات اپلوڈ کریں، اور تعلیمی اعلان کریں",
    personalInfo          = "ذاتی معلومات",
    personalInfoSub       = "شناختی کارڈ کے مطابق سرکاری تفصیلات درج کریں",
    fatherName            = "والد کا نام",
    fatherNameHint        = "اسلم خان",
    cnicNumber            = "شناختی کارڈ نمبر",
    cnicHint              = "42201-XXXXXXX-X",
    dateOfBirth           = "تاریخ پیدائش",
    dobHint               = "DD/MM/YYYY",
    contactNumber         = "رابطہ نمبر",
    cityArea              = "شہر / علاقہ",
    cityHint              = "اپنا شہر منتخب کریں",
    address               = "پتہ",
    addressHint           = "مکان نمبر، گلی نمبر، سیکٹر/علاقہ",
    ok                    = "ٹھیک ہے",
    cancel                = "منسوخ",
    docUpload             = "دستاویز اپلوڈ",
    docUploadSub          = "اصل دستاویزات کے اعلیٰ معیار کے اسکین اپلوڈ کریں",
    docWarning            = "براہ کرم یقینی بنائیں کہ تمام دستاویزات واضح ہیں۔ دھندلی یا غلط دستاویزات سے رجسٹریشن مسترد ہو سکتی ہے۔ زیادہ سے زیادہ فائل سائز: 5MB۔",
    educationDeclaration  = "تعلیمی اعلان",
    educationSub          = "کم از کم تعلیمی ضرورت 10 سال (میٹرک) ہے",
    sixteenYears          = "16 سالہ تعلیم",
    sixteenYearsSub       = "16 سالہ تعلیم والے امیدوار اعلیٰ ماڈیولز کے اہل ہیں۔",
    uploadDegree          = "ڈگری ٹرانسکرپٹ / سرٹیفکیٹ اپلوڈ کریں",
    uploadDegreeHint      = "ڈریگ اینڈ ڈراپ کریں یا براؤز کرنے کے لیے ٹیپ کریں",
    changeFile            = "فائل تبدیل کریں",
    upload                = "اپلوڈ",
    step1Label            = "مرحلہ 1 از 3 • رجسٹریشن",
    continueToPayment     = "ادائیگی جاری رکھیں",

    stepRegistration      = "رجسٹریشن",
    stepPayment           = "ادائیگی",
    stepTraining          = "ٹریننگ",
    completeProfile       = "پروفائل مکمل کریں",
    pickDate              = "تربیت کی تاریخ منتخب کریں",
    appProgress           = "درخواست کی پیشرفت",
    appProgressSub        = "سرٹیفیکیشن حاصل کرنے کے لیے تمام مراحل مکمل کریں",
    currentStepLabel      = "موجودہ مرحلہ",

    email                 = "ای میل",
    phone                 = "فون",
    location              = "مقام",
    appStatus             = "درخواست کی حیثیت",
    registrationLabel     = "رجسٹریشن",
    completed             = "مکمل",
    trainingStatus        = "تربیت کی حیثیت",
    notScheduled          = "شیڈول نہیں ہوا",
    certificate           = "سرٹیفیکیٹ",
    pendingTraining       = "تربیت زیر التواء",
    pending               = "زیر التواء",
    fatherNameLabel       = "والد کا نام",
    cnicLabel             = "شناختی کارڈ نمبر",
    dobLabel              = "تاریخ پیدائش",
    cityLabel             = "شہر",
    addressLabel          = "پتہ",
    regDateLabel          = "رجسٹریشن تاریخ",
    feePayment            = "فیس ادائیگی",
    uploadedDocs          = "اپلوڈ شدہ دستاویزات",
    view                  = "دیکھیں",
    uploaded              = "اپلوڈ",
    noDocs                = "ابھی تک کوئی دستاویز اپلوڈ نہیں ہوئی",
    completeRegForDocs    = "دستاویزات اپلوڈ کرنے کے لیے رجسٹریشن مکمل کریں",
    trainingDate          = "تربیت کی تاریخ",
    trainingTime          = "تربیت کا وقت",
    trainingCenter        = "تربیتی مرکز",
    trainingAddress       = "پتہ",
    trainingCity          = "شہر",
    trainingArrive        = "براہ کرم 15 منٹ پہلے پہنچیں اور درست شناختی کارڈ ساتھ لائیں۔",
    noteLabel             = "نوٹ:",

    trainingScheduled     = "تربیت پہلے سے شیڈول ہے",
    trainingScheduledSub  = "آپ کا تربیتی سیشن بک ہو گیا ہے۔ اپنا شیڈول دیکھنے کے لیے پروفائل ٹیب پر جائیں۔",
    goToProfile           = "پروفائل پر جائیں",

    paymentTitle          = "رجسٹریشن ادائیگی",
    paymentSub            = "اپنا کینڈیڈیٹ پروفائل فعال کرنے کے لیے ادائیگی مکمل کریں",
    registrationFee       = "رجسٹریشن فیس",
    paidBadge             = "ادا شدہ",
    generateQr            = "QR بنائیں",
    generating            = "بن رہا ہے...",
    confirmPayment        = "ادائیگی کی تصدیق کریں",
    confirming            = "تصدیق ہو رہی ہے...",
    transactionId         = "ٹرانزیکشن ID",
    paymentDate           = "ادائیگی کی تاریخ",
    paymentSuccess        = "ادائیگی کامیاب",
    downloadReceipt       = "رسید ڈاؤنلوڈ کریں",
    step2Label            = "مرحلہ 2 از 3 • ادائیگی",
    back                  = "واپس",
    continueToScheduling  = "شیڈولنگ جاری رکھیں",
    paymentProgressDone   = "رجسٹریشن",
    paymentProgressActive = "ادائیگی",
    paymentProgressPending = "تربیت شیڈول کریں",
    registrationFeeSub    = "امیدوار پروفائل کو فعال کرنے کے لیے ایک بار رجسٹریشن فیس",
    includedTaxes         = "ٹیکس شامل ہیں",
    scanQrToPay           = "PKR 5,000 ادا کرنے کے لیے QR کوڈ اسکین کریں",
    verifying             = "تصدیق ہو رہی ہے...",
    downloading           = "ڈاؤنلوڈ ہو رہا ہے...",
    statusLabel           = "حیثیت",
    successLabel          = "کامیاب",
    payFee                = "PKR 5000 ادا کریں",

    scheduleTrainingTitle = "اپنی تربیت شیڈول کریں",
    scheduleTrainingSub   = "اپنی پسندیدہ تربیتی تاریخ منتخب کریں",
    step3Label            = "مرحلہ 3 از 3 • شیڈولنگ",
    scheduling            = "شیڈول ہو رہا ہے...",
    completeRegistrationBtn = "رجسٹریشن مکمل کریں",

    regComplete           = "رجسٹریشن مکمل",
    congratulations       = "مبارک ہو! 🎉",
    regCompletedSub       = "آپ کی رجسٹریشن مکمل ہو گئی ہے اور آپ کی تربیت کامیابی سے شیڈول ہو گئی ہے",
    trainingScheduleTitle = "تربیت کا شیڈول",
    trainingScheduleCardSub = "آپ کی شیڈول تربیت کی تفصیلات",
    dateLabel             = "تاریخ",
    timeLabel             = "وقت",
    centerLabel           = "مرکز",
    whatsNext             = "آگے کیا؟",
    whatsNextItem1        = "مقررہ تاریخ پر اپنے مرکز پر جائیں",
    whatsNextItem2        = "شناختی تصدیق کے لیے اصل شناختی کارڈ ساتھ لائیں",
    whatsNextItem3        = "مرکزی ایڈمن آپ کی تربیت شروع کرے گا",
    whatsNextItem4        = "20 منٹ میں 20 سوالات - تیار رہیں!",
    badgeRegistrationSub  = "مکمل",
    badgePaymentSub       = "موصول",
    badgeTrainingSub      = "شیڈول",

    mandatory             = "لازمی",
    change                = "تبدیل کریں",
    paymentSuccessfulBanner = "ادائیگی کامیاب!",
    proceedToSchedule     = "اب آپ اپنی تربیت شیڈول کر سکتے ہیں",

    docCandidatePhoto     = "امیدوار کی تصویر",
    docCnicFront          = "شناختی کارڈ سامنے",
    docCnicBack           = "شناختی کارڈ پیچھے",
    docPassport           = "پاسپورٹ",
    docPoliceCert         = "پولیس کلیئرنس سرٹیفکیٹ",
    docMedicalCert        = "طبی سرٹیفکیٹ",

    paid                  = "ادا شدہ",
    unpaid                = "غیر ادا شدہ",

    paymentRequiredWarning = "شیڈولنگ کے لیے ادائیگی مکمل کریں",
    selectDateWarning     = "شیڈولنگ مکمل کرنے کے لیے تاریخ منتخب کریں",
    selectTrainingDateTitle = "تربیتی تاریخ منتخب کریں",
    chooseTrainingDate    = "اپنی پسندیدہ تربیتی تاریخ منتخب کریں",
    lastDaySchedule       = "امتحان شیڈول کرنے کا آخری دن!",
    daysLeftSchedule      = "دن باقی ہیں",
    daysRemainingSchedule = "دن باقی ہیں",
    selectWithinDays      = "اگلے 7 دنوں میں سے کوئی تاریخ منتخب کریں",
)

fun AppStrings.labelFor(type: DocumentType): String = when (type) {
    DocumentType.CANDIDATE_PHOTO -> docCandidatePhoto
    DocumentType.CNIC_FRONT      -> docCnicFront
    DocumentType.CNIC_BACK       -> docCnicBack
    DocumentType.PASSPORT        -> docPassport
    DocumentType.POLICE_CERT     -> docPoliceCert
    DocumentType.MEDICAL_CERT    -> docMedicalCert
}